version: '3.3'

services:
  server:
    container_name: server
    build:
      context: server
      dockerfile: back.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    expose:
      - 8000
    volumes:
    - ./server:/code
