version: '3.3'

services:
  db:
    image: mariadb
    container_name: k-tutor
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: emh4baTVMa3SYmSf
  server:
    container_name: backend
    build:
      context: server
      dockerfile: back.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    expose:
      - 8000
    volumes:
    - ./server:/code
