version: '3.3'

services:
  db:
    image: mariadb
    container_name: k-tutor
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: emh4baTVMa3SYmSf
  django:
    container_name: backend
    build:
      context: server
      dockerfile: back.Dockerfile
    command: python3 manage.py runserver 172.26.12.150:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
