version: '3.8.5'

services:
  volumes:
    k-tutor-db-volume: {}
  db:
    image: mariadb
    container_name: k-tutor2
    volumes: k-tutor-db-volume:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  django:
    container_name: backend
    build:
      context: server
      dockerfile: back.Dockerfile
    command: python3 manage.py runserver 172.26.12.150:8000
    links: k-tutor-db:sample-project-db
    volumes: ./server:/code
    ports: "8000:8000"
    depends_on: db