version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8081:8081'
    volumes:
      - .:/code
      - ./nginx:/server/nginx/conf
      - ./static_root:/static
    depends_on:
      - server
  server:
    command: bash -c 'while true; do gunicorn server.wsgi:application --bind 0.0.0.0:8000; sleep 2; done'
    container_name: backend
    working_dir: /server
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
    - ./server:/code
    - ./staticfiles:/staticfiles
    stdin_open: true
    tty: true
  client:
    container_name: frontend
    build:
      context: client
      dockerfile: front.Dockerfile
    stdin_open: true
    tty: true
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      -  ./client:/app
      - ./staticfiles:/staticfiles
