version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8081:8081'
    volumes:
      - ./server:/server
      - ./nginx.cof:/server/nginx/conf
      - ./staticfiles:/static
    depends_on:
      - server
  server:
    command: bash -c 'while true; do gunicorn server.wsgi:application --bind 0.0.0.0:8000; sleep 2; done'
    container_name: backend
    build:
      context: .
      dockerfile: back.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    expose:
      - 8000
    volumes:
      - .:/code
      - ./staticfiles:/staticfiles
    stdin_open: true
    tty: true
  db:
    image: dudrlf1859/k-tutor
    container_name: k-tutor
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: emh4baTVMa3SYmSf
    stdin_open: true
    tty: true